// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/network.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetupNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BridgeIP      string                 `protobuf:"bytes,1,opt,name=bridgeIP,proto3" json:"bridgeIP,omitempty"`
	NumVMs        int32                  `protobuf:"varint,2,opt,name=numVMs,proto3" json:"numVMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupNetworkRequest) Reset() {
	*x = SetupNetworkRequest{}
	mi := &file_proto_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupNetworkRequest) ProtoMessage() {}

func (x *SetupNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupNetworkRequest.ProtoReflect.Descriptor instead.
func (*SetupNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{0}
}

func (x *SetupNetworkRequest) GetBridgeIP() string {
	if x != nil {
		return x.BridgeIP
	}
	return ""
}

func (x *SetupNetworkRequest) GetNumVMs() int32 {
	if x != nil {
		return x.NumVMs
	}
	return 0
}

type SetupNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupNetworkResponse) Reset() {
	*x = SetupNetworkResponse{}
	mi := &file_proto_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupNetworkResponse) ProtoMessage() {}

func (x *SetupNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupNetworkResponse.ProtoReflect.Descriptor instead.
func (*SetupNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{1}
}

type CleanupNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumVMs        int32                  `protobuf:"varint,1,opt,name=numVMs,proto3" json:"numVMs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupNetworkRequest) Reset() {
	*x = CleanupNetworkRequest{}
	mi := &file_proto_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupNetworkRequest) ProtoMessage() {}

func (x *CleanupNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupNetworkRequest.ProtoReflect.Descriptor instead.
func (*CleanupNetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{2}
}

func (x *CleanupNetworkRequest) GetNumVMs() int32 {
	if x != nil {
		return x.NumVMs
	}
	return 0
}

type CleanupNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupNetworkResponse) Reset() {
	*x = CleanupNetworkResponse{}
	mi := &file_proto_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupNetworkResponse) ProtoMessage() {}

func (x *CleanupNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupNetworkResponse.ProtoReflect.Descriptor instead.
func (*CleanupNetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{3}
}

type SetupCrossNodeRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RemoteSubnet  string                 `protobuf:"bytes,1,opt,name=remoteSubnet,proto3" json:"remoteSubnet,omitempty"`
	RemoteNodeIP  string                 `protobuf:"bytes,2,opt,name=remoteNodeIP,proto3" json:"remoteNodeIP,omitempty"`
	LocalBridgeIP string                 `protobuf:"bytes,3,opt,name=localBridgeIP,proto3" json:"localBridgeIP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupCrossNodeRouteRequest) Reset() {
	*x = SetupCrossNodeRouteRequest{}
	mi := &file_proto_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupCrossNodeRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupCrossNodeRouteRequest) ProtoMessage() {}

func (x *SetupCrossNodeRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupCrossNodeRouteRequest.ProtoReflect.Descriptor instead.
func (*SetupCrossNodeRouteRequest) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{4}
}

func (x *SetupCrossNodeRouteRequest) GetRemoteSubnet() string {
	if x != nil {
		return x.RemoteSubnet
	}
	return ""
}

func (x *SetupCrossNodeRouteRequest) GetRemoteNodeIP() string {
	if x != nil {
		return x.RemoteNodeIP
	}
	return ""
}

func (x *SetupCrossNodeRouteRequest) GetLocalBridgeIP() string {
	if x != nil {
		return x.LocalBridgeIP
	}
	return ""
}

type SetupCrossNodeRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupCrossNodeRouteResponse) Reset() {
	*x = SetupCrossNodeRouteResponse{}
	mi := &file_proto_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupCrossNodeRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupCrossNodeRouteResponse) ProtoMessage() {}

func (x *SetupCrossNodeRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupCrossNodeRouteResponse.ProtoReflect.Descriptor instead.
func (*SetupCrossNodeRouteResponse) Descriptor() ([]byte, []int) {
	return file_proto_network_proto_rawDescGZIP(), []int{5}
}

var File_proto_network_proto protoreflect.FileDescriptor

const file_proto_network_proto_rawDesc = "" +
	"\n" +
	"\x13proto/network.proto\x12\x10proto.network.v1\"I\n" +
	"\x13SetupNetworkRequest\x12\x1a\n" +
	"\bbridgeIP\x18\x01 \x01(\tR\bbridgeIP\x12\x16\n" +
	"\x06numVMs\x18\x02 \x01(\x05R\x06numVMs\"\x16\n" +
	"\x14SetupNetworkResponse\"/\n" +
	"\x15CleanupNetworkRequest\x12\x16\n" +
	"\x06numVMs\x18\x01 \x01(\x05R\x06numVMs\"\x18\n" +
	"\x16CleanupNetworkResponse\"\x8a\x01\n" +
	"\x1aSetupCrossNodeRouteRequest\x12\"\n" +
	"\fremoteSubnet\x18\x01 \x01(\tR\fremoteSubnet\x12\"\n" +
	"\fremoteNodeIP\x18\x02 \x01(\tR\fremoteNodeIP\x12$\n" +
	"\rlocalBridgeIP\x18\x03 \x01(\tR\rlocalBridgeIP\"\x1d\n" +
	"\x1bSetupCrossNodeRouteResponse2\xc0\x02\n" +
	"\x0eNetworkService\x12X\n" +
	"\x05Setup\x12%.proto.network.v1.SetupNetworkRequest\x1a&.proto.network.v1.SetupNetworkResponse\"\x00\x12^\n" +
	"\aCleanup\x12'.proto.network.v1.CleanupNetworkRequest\x1a(.proto.network.v1.CleanupNetworkResponse\"\x00\x12t\n" +
	"\x13SetupCrossNodeRoute\x12,.proto.network.v1.SetupCrossNodeRouteRequest\x1a-.proto.network.v1.SetupCrossNodeRouteResponse\"\x00B\x12Z\x10proto/network/v1b\x06proto3"

var (
	file_proto_network_proto_rawDescOnce sync.Once
	file_proto_network_proto_rawDescData []byte
)

func file_proto_network_proto_rawDescGZIP() []byte {
	file_proto_network_proto_rawDescOnce.Do(func() {
		file_proto_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_network_proto_rawDesc), len(file_proto_network_proto_rawDesc)))
	})
	return file_proto_network_proto_rawDescData
}

var file_proto_network_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_network_proto_goTypes = []any{
	(*SetupNetworkRequest)(nil),         // 0: proto.network.v1.SetupNetworkRequest
	(*SetupNetworkResponse)(nil),        // 1: proto.network.v1.SetupNetworkResponse
	(*CleanupNetworkRequest)(nil),       // 2: proto.network.v1.CleanupNetworkRequest
	(*CleanupNetworkResponse)(nil),      // 3: proto.network.v1.CleanupNetworkResponse
	(*SetupCrossNodeRouteRequest)(nil),  // 4: proto.network.v1.SetupCrossNodeRouteRequest
	(*SetupCrossNodeRouteResponse)(nil), // 5: proto.network.v1.SetupCrossNodeRouteResponse
}
var file_proto_network_proto_depIdxs = []int32{
	0, // 0: proto.network.v1.NetworkService.Setup:input_type -> proto.network.v1.SetupNetworkRequest
	2, // 1: proto.network.v1.NetworkService.Cleanup:input_type -> proto.network.v1.CleanupNetworkRequest
	4, // 2: proto.network.v1.NetworkService.SetupCrossNodeRoute:input_type -> proto.network.v1.SetupCrossNodeRouteRequest
	1, // 3: proto.network.v1.NetworkService.Setup:output_type -> proto.network.v1.SetupNetworkResponse
	3, // 4: proto.network.v1.NetworkService.Cleanup:output_type -> proto.network.v1.CleanupNetworkResponse
	5, // 5: proto.network.v1.NetworkService.SetupCrossNodeRoute:output_type -> proto.network.v1.SetupCrossNodeRouteResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_network_proto_init() }
func file_proto_network_proto_init() {
	if File_proto_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_network_proto_rawDesc), len(file_proto_network_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_network_proto_goTypes,
		DependencyIndexes: file_proto_network_proto_depIdxs,
		MessageInfos:      file_proto_network_proto_msgTypes,
	}.Build()
	File_proto_network_proto = out.File
	file_proto_network_proto_goTypes = nil
	file_proto_network_proto_depIdxs = nil
}
